Repository AY2223S2-CS2103T-W09-2/tp, pull requests merged in 2023-03, with the labels that each got.

#63 Add expense storage class
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/category/MiscellaneousCategory.java
  src/main/java/seedu/address/model/category/UserDefinedCategory.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/test/java/seedu/address/model/category/CategoryTest.java
  src/test/java/seedu/address/model/category/MiscellaneousCategoryTest.java
  src/test/java/seedu/address/model/category/UserDefinedCategoryTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
Labels: priority.high, type.functionality

#64 Expense Class
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/category/MiscellaneousCategory.java
  src/main/java/seedu/address/model/category/UserDefinedCategory.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/test/java/seedu/address/model/category/CategoryTest.java
  src/test/java/seedu/address/model/category/MiscellaneousCategoryTest.java
  src/test/java/seedu/address/model/category/UserDefinedCategoryTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
Labels: priority.high

#66 Update Help Window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.medium, type.functionality

#76 Add JavaDocs and refactor
  data/addressbook.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCategory.java
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCategory.java
  src/main/java/seedu/address/logic/commands/DeleteExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseTrackerParser.java
  src/main/java/seedu/address/model/ExpenseTracker.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyExpenseTracker.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/category/MiscellaneousCategory.java
  src/main/java/seedu/address/model/category/UniqueCategoryList.java
  src/main/java/seedu/address/model/category/UserDefinedCategory.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/ExpenseTrackerStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedCategory.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonExpenseTrackerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseTracker.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, type.documentation

#90 Find command Closes #46
  README.md
  data/addressbook.json
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/shirsho-12.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseTrackerParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/expense/ExpenseContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/expense/ExpenseContainsKeywordsPredicateTest.java
Labels: priority.high, type.functionality

#92 Add category and expense command tests
  src/main/java/seedu/address/logic/commands/AddCategory.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/test/java/seedu/address/commons/stubs/ModelStub.java
  src/test/java/seedu/address/logic/commands/AddCategoryCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCategoryCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteExpenseCommandTest.java
  src/test/java/seedu/address/model/category/MiscellaneousCategoryTest.java
  src/test/java/seedu/address/model/expense/ExpenseListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCategoryTest.java
  src/test/java/seedu/address/storage/JsonExpenseTrackerStorageTest.java
Labels: bug, duplicate, priority.high

#100 Fix wrong association bug and add edit category functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCategory.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCategoryParser.java
  src/main/java/seedu/address/logic/parser/ExpenseTrackerParser.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseTracker.java
  src/main/java/seedu/address/ui/ExpenseListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/stubs/ModelStub.java
  src/test/java/seedu/address/logic/commands/EditCategoryTest.java
Labels: bug, priority.high, type.functionality

#102 Update DG - minor - shirsho
  docs/DeveloperGuide.md
Labels: priority.low, type.documentation

#103 Add DG update for Edit Category feature
  docs/DeveloperGuide.md
Labels: priority.low, type.documentation

#111 Add expense summary statistics feature Closes #82
  data/addressbook.json
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCategoryCommand.java
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCategoryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExpenseCommand.java
  src/main/java/seedu/address/logic/commands/EditCategory.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AnalyticModel.java
  src/main/java/seedu/address/model/AnalyticModelManager.java
  src/main/java/seedu/address/model/ExpenseTracker.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/category/UniqueCategoryList.java
  src/main/java/seedu/address/model/util/AnalyticsType.java
  src/main/java/seedu/address/model/util/UserInterfaceUtil.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseTracker.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/CategoryCard.java
  src/main/java/seedu/address/ui/CategoryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultsDetails.java
  src/main/java/seedu/address/ui/StatisticsPanel.java
  src/main/resources/view/CategoryListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpenseListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsPanel.fxml
  src/test/java/seedu/address/commons/stubs/ModelStub.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCategoryCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCategoryCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCategoryTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/AnalyticModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: priority.high, type.functionality

#114 Add edit expense command functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditExpenseCommand.java
  src/main/java/seedu/address/logic/parser/EditExpenseCommandParser.java
  src/main/java/seedu/address/model/util/SampleExpenseTracker.java
  src/test/java/seedu/address/logic/commands/EditExpenseCommandTest.java
Labels: priority.medium, type.functionality

#121 Update UG for Features
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.documentation

#118 Optional summary when adding Category
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/AddCategoryCommand.java
  src/main/java/seedu/address/logic/parser/AddCategoryParser.java
Labels: priority.medium, type.functionality

#139 Add storage functionality for recurring expenses.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ExpenseTracker.java
  src/main/java/seedu/address/model/ReadOnlyExpenseTracker.java
  src/main/java/seedu/address/model/expense/RecurringExpenseList.java
  src/main/java/seedu/address/model/expense/RecurringExpenseManager.java
  src/main/java/seedu/address/model/expense/RecurringExpenseType.java
  src/main/java/seedu/address/storage/JsonAdaptedRecurringExpenseManager.java
  src/main/java/seedu/address/storage/JsonExpenseTrackerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseTracker.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.medium, type.functionality

#151 Refactoring code for release 1.3
  data/addressbook.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/AddRecurringExpenseCommand.java
  src/main/java/seedu/address/logic/commands/EditCategory.java
  src/main/java/seedu/address/logic/commands/EditExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/model/AnalyticModel.java
  src/main/java/seedu/address/model/AnalyticModelManager.java
  src/main/java/seedu/address/model/util/SampleExpenseTracker.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/StatisticsPanel.java
  src/main/resources/view/ExpenseListCard.fxml
  src/main/resources/view/RecurringExpenseListCard.fxml
Labels: priority.medium, type.functionality

#152 reformat ug and fix some invalid syntax
  docs/UserGuide.md
  docs/images/fasttrack_labeled_1.png
  docs/images/fasttrack_labeled_2.png
  docs/images/fasttrack_labeled_3.png
Labels: priority.high, type.documentation
